name: IICS_CD
on:
 push:
   branches:
      - dev
  
  #workflow_dispatch:
    #inputs:
      #committed_sha:
        #description: "Hash to deploy"
        #type: string
        #required: true

env:
  IICS_LOGIN_URL: https://dm2-us.informaticacloud.com
  IICS_POD_URL: https://usw1.dm2-us.informaticacloud.com
 
  IICS_USERNAME: ${{ secrets.IICS_USERNAME }}
  IICS_PASSWORD: ${{ secrets.IICS_PASSWORD }}

  # This is overriding until we connect the repository with a workflow_dispatch

  COMMIT_HASH: ${{  github.event.inputs.committed_sha }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dev_build:
    name: Review Development Code
    environment:
      name: dev
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Python and dependent modules
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - name: Install python modules
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      # Runs a single command using the runner's shell
      - name: Login to development 
        run: |
            python ./script/infa_login.py

      - name: Set default username
        run: git config --global user.email "ratnakarpatelz@gmail.com"; git config --global user.name "Ratnakar"

      - name: Commit changes to UAT
        run: cd ./IICS_2; git fetch --all; git cherry-pick --strategy=recursive -X theirs ${COMMIT_HASH}; git push

      - name: Get the latest UAT to commit hash
        run: cd ./IICS-2; git pull; echo "COMMIT_HASH=$(git log -1 --pretty=format:%H)" >> $GITHUB_ENV
